In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the vocubalaru size

voc_size=10000

In [51]:
voc_size

10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [37]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2872, 6250, 9623, 8795],
 [2872, 6250, 9623, 1353],
 [2872, 5282, 9623, 7510],
 [7356, 4799, 2158, 7864, 2841],
 [7356, 4799, 2158, 7864, 5795],
 [9756, 2872, 1528, 9623, 3440],
 [5607, 5310, 9262, 7864]]

In [38]:
one_hot_rep

[[2872, 6250, 9623, 8795],
 [2872, 6250, 9623, 1353],
 [2872, 5282, 9623, 7510],
 [7356, 4799, 2158, 7864, 2841],
 [7356, 4799, 2158, 7864, 5795],
 [9756, 2872, 1528, 9623, 3440],
 [5607, 5310, 9262, 7864]]

In [9]:
# word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [39]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2872 6250 9623 8795]
 [   0    0    0    0 2872 6250 9623 1353]
 [   0    0    0    0 2872 5282 9623 7510]
 [   0    0    0 7356 4799 2158 7864 2841]
 [   0    0    0 7356 4799 2158 7864 5795]
 [   0    0    0 9756 2872 1528 9623 3440]
 [   0    0    0    0 5607 5310 9262 7864]]


In [42]:
embedded_docs

array([[   0,    0,    0,    0, 2872, 6250, 9623, 8795],
       [   0,    0,    0,    0, 2872, 6250, 9623, 1353],
       [   0,    0,    0,    0, 2872, 5282, 9623, 7510],
       [   0,    0,    0, 7356, 4799, 2158, 7864, 2841],
       [   0,    0,    0, 7356, 4799, 2158, 7864, 5795],
       [   0,    0,    0, 9756, 2872, 1528, 9623, 3440],
       [   0,    0,    0,    0, 5607, 5310, 9262, 7864]])

In [43]:
## feature representation
dim=10

In [44]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [45]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 681ms/step


array([[[-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [ 0.00457992,  0.01706742,  0.02455037, -0.03275573,
          0.00055168, -0.02016922, -0.01175287,  0.00771749,
          0.01339599, -0.026782  ],
        [ 0.04360307, -0.03248965,  0.02464269,  0.04518706,
          0.00763546, -0.01475506, -0.03089362, -0.01131422,
          0.04451304, -0.00236688],
        [-0.00707459,  0.01533679, -0.01454196, -0.0

In [47]:
embedded_docs[0]

array([   0,    0,    0,    0, 2872, 6250, 9623, 8795])

In [50]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step


array([[[-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [ 0.00457992,  0.01706742,  0.02455037, -0.03275573,
          0.00055168, -0.02016922, -0.01175287,  0.00771749,
          0.01339599, -0.026782  ],
        [ 0.04360307, -0.03248965,  0.02464269,  0.04518706,
          0.00763546, -0.01475506, -0.03089362, -0.01131422,
          0.04451304, -0.00236688],
        [-0.00707459,  0.01533679, -0.01454196, -0.0

In [49]:
import numpy as np

embedded_docs = np.expand_dims(embedded_docs[0], axis=0)  # Add batch dimension
model.predict(embedded_docs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step


array([[[-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [-0.03784146, -0.0487438 ,  0.00524295, -0.04964942,
          0.0382488 ,  0.00493137,  0.04181204,  0.02761403,
         -0.00342008, -0.00559532],
        [ 0.00457992,  0.01706742,  0.02455037, -0.03275573,
          0.00055168, -0.02016922, -0.01175287,  0.00771749,
          0.01339599, -0.026782  ],
        [ 0.04360307, -0.03248965,  0.02464269,  0.04518706,
          0.00763546, -0.01475506, -0.03089362, -0.01131422,
          0.04451304, -0.00236688],
        [-0.00707459,  0.01533679, -0.01454196, -0.0